### ISSUE TITLE
remove scripts from html attributes

### ISSUE THREAD

**Issue by tommedema** [eperegrine/script_sanitizer.js#1]
have you considered to include support for this?

e.g. `<a href="#" onclick="hello()">click me</a>`

should result in `<a href="#">click me</a>`

**Comment by eperegrine** [comment]
That has been possible for a while via the use of the `attributes` parameter, but I have jut pushed an update that adds a lot of default attributes including onclick

**Comment by tommedema** [comment]
@eperegrine fantastic, much appreciated
